---
- hosts: localhost
  connection: local

  vars:
    vagrant:
      version: 2.2.10
    golang:
      version: 1.15.3

  tasks:
    - name: Install Base Packages
      become: true
      import_tasks: tasks/sys-packages.yml
      tags:
        - packages

    - name: Golang
      become: true
      import_tasks: tasks/golang.yml
      tags:
        - golang

    - name: Install Virtualbox
      become: true
      import_tasks: tasks/virtualbox.yml
      tags:
        - virtualbox
        - vbox

    - name: Install Docker
      become: true
      import_tasks: tasks/docker.yml
      tags:
        - docker

    - name: Install Vagrant
      import_tasks: tasks/vagrant.yml
      tags:
        - vagrant

  handlers:
    - name: Start/Restart Docker
      become: true
      service:
        name: docker
        state: restarted
