- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: auto
    docker_users:
      - "{{ ansible_user_id }}"

  pre_tasks:
    - name: Create Local User
      ansible.builtin.include_tasks: tasks/user.yml
      args:
        apply:
          become: yes
          tags:
            - user
      tags:
        - user

    - name: Base packages
      ansible.builtin.include_tasks: tasks/base_packages.yml
      args:
        apply:
          become: yes
          tags:
            - base_packages
      tags:
        - base_packages

    - name: Include yubico
      ansible.builtin.include_tasks: tasks/yubico.yml
      args:
        apply:
          become: yes
          tags:
            - yubico
      tags:
        - yubico

    - name: Include nvim
      ansible.builtin.include_tasks: tasks/nvim.yml
      args:
        apply:
          become: yes
          tags:
            - nvim
      tags:
        - nvim

    - name: Include delta
      ansible.builtin.include_tasks: tasks/delta.yml
      args:
        apply:
          become: yes
          tags:
            - delta
      tags:
        - delta

    - name: Include ripgrep 
      ansible.builtin.include_tasks: tasks/rg.yml
      args:
        apply:
          become: yes
          tags:
            - rg 
      tags:
        - rg

    - name: Include direnv
      ansible.builtin.include_tasks: tasks/direnv.yml
      args:
        apply:
          become: yes
          tags:
            - direnv
      tags:
        - direnv

    - name: Include bat
      ansible.builtin.include_tasks: tasks/bat.yml
      args:
        apply:
          become: yes
          tags:
            - bat
      tags:
        - bat

    - name: Include OMZ
      ansible.builtin.include_tasks: tasks/omz.yml
      args:
        apply:
          tags:
            - omz
      tags:
        - omz

    - name: Include FZF
      ansible.builtin.include_tasks: tasks/fzf.yml
      args:
        apply:
          tags:
            - fzf
      tags:
        - fzf

  roles:
      - { role: geerlingguy.docker, become: true }
