---
- hosts: localhost
  connection: local

  pre_tasks:
    - name: Include vars
      include_vars:
        dir: vars
        ignore_unknown_extensions: true
        extensions:
          - 'yml'
      tags:
        - always

  tasks:
    - name: Install Base Packages
      become: true
      import_tasks: tasks/sys-packages.yml
      tags:
        - packages
        - system

    - name: Golang
      become: true
      import_tasks: tasks/golang.yml
      tags:
        - golang
        - system

    - name: Install Virtualbox
      become: true
      import_tasks: tasks/virtualbox.yml
      tags:
        - virtualbox
        - vbox
        - system

    - name: Install Docker
      become: true
      import_tasks: tasks/docker.yml
      tags:
        - docker
        - system

    - name: Install Vagrant
      import_tasks: tasks/vagrant.yml
      tags:
        - vagrant
        - system

  handlers:
    - name: Start/Restart Docker
      become: true
      service:
        name: docker
        state: restarted

  roles:
    - role: zzet.rbenv
      tags:
        - rbenv
