---
- hosts: localhost
  connection: local

  pre_tasks:
    - name: Include vars
      include_vars:
        dir: vars
        ignore_unknown_extensions: true
        extensions:
          - 'yml'
      tags:
        - always

  tasks:
    - name: Install Base Packages
      become: true
      import_tasks: tasks/sys-packages.yml
      tags:
        - packages
        - system

    - name: Golang
      become: true
      import_tasks: tasks/golang.yml
      tags:
        - golang
        - system

    - name: Install Virtualbox
      become: true
      import_tasks: tasks/virtualbox.yml
      tags:
        - virtualbox
        - vbox
        - system

    - name: Install Docker
      become: true
      import_tasks: tasks/docker.yml
      tags:
        - docker
        - system

    - name: Install NVIM
      become: true
      import_tasks: tasks/nvim.yml
      tags:
        - nvim
        - system

    - name: Install P10K Fonts
      import_tasks: tasks/p10kfonts.yml
      tags:
        - user
        - p10k
        - fonts

    - name: Install Vagrant
      import_tasks: tasks/vagrant.yml
      tags:
        - vagrant
        - user

    - name: Install Packer
      import_tasks: tasks/packer.yml
      tags:
        - packer
        - user

    - name: Install Delta
      import_tasks: tasks/delta.yml
      tags:
        - delta
        - user

    - name: Install Hub
      import_tasks: tasks/hub.yml
      tags:
        - hub
        - user

    - name: Install AWS CLI v2
      import_tasks: tasks/awscliv2.yml
      tags:
        - awscli
        - aws
        - awscliv2
        - user

    - name: Install Neovim Gems
      gem:
        name: neovim
      environment:
        PATH: "{{ ansible_env.HOME }}/.shims/bin:{{ ansible_env.PATH }}"
      tags:
        - user
        - ruby
        - gems
        - gem

  handlers:
    - name: Start/Restart Docker
      become: true
      service:
        name: docker
        state: restarted

    - name: Rebuild Fonts
      become: true
      command: 'fc-cache -v -f'


  roles:
    - role: zzet.rbenv
      tags:
        - rbenv
