- hosts: localhost
  vars:
    docker_users:
      - "{{ ansible_user_id }}"

  pre_tasks:
    - name: Base packages
      ansible.builtin.include_tasks: tasks/base_packages.yml
      args:
        apply:
          become: yes
          tags:
            - base_packages
      tags:
        - base_packages

    - name: Include yubico
      ansible.builtin.include_tasks: tasks/yubico.yml
      args:
        apply:
          become: yes
          tags:
            - yubico
      tags:
        - yubico

    - name: Include delta
      ansible.builtin.include_tasks: tasks/delta.yml
      args:
        apply:
          become: yes
          tags:
            - delta
      tags:
        - delta

    - name: Include OMZ
      ansible.builtin.include_tasks: tasks/omz.yml
      args:
        apply:
          tags:
            - omz
      tags:
        - omz

  roles:
      - { role: geerlingguy.docker, become: true }
