---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: auto

  vars_files:
    - vars/common.yml

  tasks:

    - name: Gather Package Facts
      package_facts:
        manager: auto

    - name: Install base workstation packages
      import_tasks: tasks/base_packages.yml
      become: true
      when: ansible_env.WORKSTATION is defined
      tags:
        - packages

    - name: Install Yubico Tools
      import_tasks: tasks/yubico.yml
      become: true
      when: ansible_env.WORKSTATION is defined
      tags:
        - yubico
        - yubikey

    - name: Update Alternatives
      import_tasks: tasks/alternatives.yml
      become: true
      when: ansible_env.WORKSTATION is defined

    - name: Install docker
      import_tasks: tasks/docker.yml
      become: true
      when: ansible_env.WORKSTATION is defined

    - name: Install Go
      import_tasks: tasks/go.yml
      become: true
      when: ansible_env.WORKSTATION is defined

    - name: Install AWS CLI
      import_tasks: tasks/aws_cli.yml
      become: true
      when:
        - ansible_env.WORKSTATION is defined
        - not ansible_check_mode

    - name: Install 1P CLI
      import_tasks: tasks/1password.yml
      become: true
      when: ansible_env.WORKSTATION is defined
      tags:
        - 1p

    - name: Install Local User and Group Membership
      import_tasks: tasks/user.yml
      become: true
      when: ansible_env.WORKSTATION is defined
      tags:
        - user

    - name: Install User Packages
      import_tasks: tasks/user_packages.yml
      tags:
        - user

    - name: Install Terraform
      import_tasks: tasks/terraform.yml
      become: true
      become_user: "{{ user }}"
      tags:
        - tf
    - name: Install Terragrunt
      import_tasks: tasks/terragrunt.yml
      become: true
      become_user: "{{ user }}"
      tags:
        - tg
