---
- name: Install Apt Packages
  apt:
    force_apt_get: true
    update_cache: true
    pkg:
      - curl
      - neovim
      - i3
      - zsh
      - fonts-powerline
      - python3-gpg
      - gnupg2
      - gnupg-agent
      - pinentry-curses
      - scdaemon
      - pcscd
      - libusb-dev
      - dex
      - net-tools
      - python3-distutils
      - python-dev
      - python3-dev
      - fonts-firacode
      - usbmount
      - jq
      - xautolock
      - blueman
      - python3-pip
      - chromium-browser
      - autorandr
      - tlp
      - rofi

- name: Install Chrome
  apt:
    force_apt_get: true
    # yamllint disable-line rule:line-length
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  when: "'google-chrome-stable' not in ansible_facts.packages"

- name: Install Keybase
  apt:
    force_apt_get: true
    deb: https://prerelease.keybase.io/keybase_amd64.deb
  when: "'keybase' not in ansible_facts.packages"

- name: Install Zoom
  apt:
    force_apt_get: true
    deb: https://zoom.us/client/latest/zoom_amd64.deb
  when: "'zoom' not in ansible_facts.packages"

- name: Install Dropbox
  apt:
    force_apt_get: true
    # yamllint disable-line rule:line-length
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.02.14_amd64.deb
  when: "'dropbox' not in ansible_facts.packages"

- name: Install delta
  apt:
    force_apt_get: true
    # yamllint disable-line rule:line-length
    deb: https://github.com/dandavison/delta/releases/download/0.1.1/git-delta_0.1.1_amd64.deb
  when: "'delta' not in ansible_facts.packages"

- name: Install hub
  snap:
    name: hub
    classic: true

- name: Install Slack
  snap:
    name: slack
    classic: true

- name: Install pre-commit
  pip:
    name: pre-commit

- name: Remove Unused Packages
  apt:
    force_apt_get: true
    autoclean: true
