---
- name: "(Bat) Check if Bat Present"
  stat:
    path: "{{ ansible_env.HOME }}/.local/bin/bat"
  register: bat_stat
  check_mode: false

- name: "(Bat) Check Bat Version"
  command: "{{ ansible_env.HOME }}/.local/bin/bat --version"
  register: delta_ver
  check_mode: false
  when: bat_stat.stat.exists
  changed_when: false
  failed_when: false

- name: "(Bat) Download and Install Bat {{ bat.version }}"
  unarchive:
    remote_src: true
    src: "https://github.com/sharkdp/bat/releases/download/v{{ bat.version }}/bat-v{{ bat.version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: 0755
    extra_opts:
      - --strip-components=1
      - --wildcards
      - --no-anchored
      - 'bat'
  when:
    - not bat_stat.stat.exists or
      bat_ver is skipped or
      bat.version not in bat_ver.stdout
