---
- name: "(Delta) Check if Delta Present"
  stat:
    path: "{{ ansible_env.HOME }}/.local/bin/delta"
  register: delta_stat
  check_mode: false

- name: "(Delta) Check Delta Version"
  command: "{{ ansible_env.HOME }}/.local/bin/delta --version"
  register: delta_ver
  check_mode: false
  when: delta_stat.stat.exists
  changed_when: false
  failed_when: false

- name: "(Delta) Download and Install Delta {{ delta.version }}"
  unarchive:
    remote_src: true
    src: "https://github.com/dandavison/delta/releases/download/0.4.4/delta-{{ delta.version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: 0755
  when:
    - not delta_stat.stat.exists or
      delta_ver is skipped or
      delta.version not in delta_ver.stdout
