---
- name: (Docker) Install prequisites
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: true

- name: (Docker) Install Docker GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: (Docker) Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: (Docker) Install Docker Engine
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
  notify:
    - Start/Restart Docker

- name: (Docker) Start Docker On Boot
  service:
    name: docker
    enabled: true

- name: (Docker) Create Docker Group
  group:
    name: docker
    state: present

- name: (Docker) Add User to Group
  user:
    name: hootieben
    groups:
      - docker
    append: true
