---
- name: Download FZF
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: "/home/{{ ansible_user_id }}/.fzf"

- name: Run FZF Install
  ansible.builtin.shell:
    cmd: "/home/{{ ansible_user_id }}/.fzf/install"
