---
- name: Check if tfenv exists
  stat:
    path: "{{ ansible_env.HOME }}/.tfenv/bin/tfenv"
  register: tfenv
  tags:
    - tf
    - tfenv

- name: Install TFENV and Terraform
  block:
    - name: Install TFENV
      git:
        repo: https://github.com/tfutils/tfenv.git
        dest: "{{ ansible_env.HOME }}/.tfenv"
        update: false
        version: v2.0.0
    - name: Get Terraform
      command: "{{ ansible_env.HOME }}/.tfenv/bin/tfenv install {{ tfver }}"
  when: not tfenv.stat.exists
  tags:
    - tf
    - tfenv
