---
- name: Check if tgenv exists
  stat:
    path: "{{ ansible_env.HOME }}/.tgenv/bin/tgenv"
  register: tgenv
  tags:
    - tg
    - tgenv

- name: Install TGENV and Terragrunt
  block:
    - name: Install TGENV
      git:
        repo: https://github.com/cunymatthieu/tgenv.git
        dest: "{{ ansible_env.HOME }}/.tgenv"
        update: false
        version: v0.0.3
    - name: Install Terragrunt
      command: "{{ ansible_env.HOME }}/.tgenv/bin/tgenv install {{ tgver }}"
      environment:
        PATH: '{{ ansible_env.HOME }}/.tgenv/bin:{{ ansible_env.PATH }}'
  when: not tgenv.stat.exists
  tags:
    - tg
    - tgenv
