---
- name: Check Terragrunt Install
  block:
    - include_tasks: terraform_test.yml
  rescue:
    - name: Install TFENV
      git:
        repo: https://github.com/tfutils/tfenv.git
        dest: "~{{ user }}/.tfenv"
        version: "v{{ tfenv_ver }}"
        force: true
    - include_tasks: terraform_test.yml
  tags:
    - tf
    - tfenv

- name: Get Installed Terraform Versions
  command: "~{{ user }}/.tfenv/bin/tfenv list"
  changed_when: false
  register: tf_installed
  when: tfenv_installed

- name: Get Terraform
  command: "~{{ user }}/.tfenv/bin/tfenv install {{ tfver }}"
  when: tfver not in tf_installed.stdout
  tags:
    - tf
    - tfenv
