---
- name: Create local bin dir
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory


- name: Check if Kitty Exists
  stat:
    path: "{{ ansible_env.HOME }}/.local/kitty.app"
  register: kitty_app
  tags:
    - kitty

- name: Install Kitty Shell
  # yamllint disable rule:line-length
  shell: |
    set -o pipefail
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin dest={{ ansible_env.HOME }}/.local launch=n
  # yamllint enable rule:line-length
  args:
    warn: false
    executable: /bin/bash
  when: not kitty_app.stat.exists
  tags:
    - kitty

- name: Get diff-so-fancy
  get_url:
    url: https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy  # yamllint disable-line rule:line-length
    dest: "{{ ansible_env.HOME }}/.local/bin/diff-so-fancy"
    mode: '0755'
