---
- name: Add Yubico Repo
  apt_repository:
    repo: 'ppa:yubico/stable'

- name: Install Yubico Tools
  apt:
    force_apt_get: true
    update_cache: true
    pkg:
      - yubikey-manager
      - yubikey-personalization-gui
      - libpam-u2f
      - libpam-yubico
