- name: Get AWS CLI
  unarchive:
      src: https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
      dest: /tmp
      remote_src: yes

- name: Install AWS CLI
  command: /tmp/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
