- name: Install Clight Dependencies
  apt:
      force_apt_get: true
      update_cache: yes
      pkg:
          - build-essential
          - cmake
          - libsystemd-dev
          - libpopt-dev
          - libconfig-dev
          - libgsl-dev
          - dh-autoreconf
          - libglib2.0-dev
          - libudev-dev
          - libusb-1.0.0-dev
          - libx11-dev
          - libxrandr-dev
          - libpolkit-gobject-1-dev
          - libdbus-1-dev
          - libdrm-dev

- name: Get Clight Install Script
  get_url:
      url: https://gist.githubusercontent.com/hootieben/2b0cde9f0a41343381b3b34389cbc8ea/raw/38fd424cdf8a27821e2ede99f91feedd571861ac/clight-install.sh
      dest: /tmp/clight-install.sh
      mode '0755'

- name: Clight Compile and Install
  command: /tmp/clight-install.sh
