- name: Get NM Config
  shell: NetworkManager --print-config
  register: nmconfig

- name: debug
  debug:
    var: nmconfig

- name: Test NM Config Location
  stat:
    path: /etc/NetworkManager/NetworkManager.conf
  register: nmc


- name: Install dnsmasq
  apt:
    force_apt_get: true
    update_cache: yes
    pkg:
      - dnsmasq
  when: nmc.stat.exists

- name: Disable systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
  register: sdr
  when: nmc.stat.exists

- name: Disable dnsmasq
  systemd:
    name: dnsmasq
    state: stopped
    enabled: false
  when: 
    - sdr.changed
    - nmc.stat.exists

- name: Set NM Config
  lineinfile:
    name: /etc/NetworkManager/NetworkManager.conf
    regexp: '^dns='
    line: dns=dnsmasq
    state: present
    insertafter: '^[main]'
  when: nmc.stat.exists
  register: nmdnsmasq

- name: Restart NM
  systemd:
    name: NetworkManager
    state: restarted
  when: nmdnsmasq.changed

- name: Set resolv.conf
  file:
    src: /var/run/NetworkManager/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
  when: nmdnsmasq.changed
