- name: Install Docker Apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: Install Docker
  apt:
    force_apt_get: true
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Start Docker on boot
  systemd:
    enabled: true
    state: started
    name: docker


- name: Create Docker Group
  group:
    name: docker
