---
- name: Check for Go installation
  stat:
    path: /usr/local/go
  register: g


- name: Get and Unarchive Go
  unarchive:
    src: "https://dl.google.com/go/go{{ golangver }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: true
  when: g.stat.isdir is not defined
