- name: Create local bin dir
  file:
      path: "{{ lu.home }}/.local/bin"
      state: directory


- name: Check if Kitty Exists
  stat:
    path: "{{ lu.home }}/.local/kitty.app"
  register: kitty_app
- name: Install Kitty Shell
  shell: "curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin dest={{ lu.home }}/.local launch=n"
  args:
    warn: false
  when: kitty_app.stat.exists == false

- name: Get diff-so-fancy
  get_url:
      url: https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
      dest: "{{ lu.home }}/.local/bin/diff-so-fancy"
      mode: '0755'

- name: Get tfenv
  git:
      repo: https://github.com/tfutils/tfenv.git
      dest: "{{ lu.home }}/.tfenv"
      update: no
  tags:
    - tf

- name: Get Terraform
  command: "{{ lu.home }}/.tfenv/bin/tfenv install {{ tfver }}"
  tags:
    - tf

- name: Get tgenv
  git:
      repo: https://github.com/cunymatthieu/tgenv.git
      dest: "{{ lu.home }}/.tgenv"
      update: no
  tags:
    - tg

- name: Get Terragrunt
  command: "{{ lu.home }}/.tgenv/bin/tgenv install {{ tgver }}"
  environment:
    PATH: '{{ lu.home }}/.tgenv/bin:{{ ansible_env.PATH }}'
  tags:
    - tg
