- hosts: localhost
  tasks:

    - name: Gather Package Facts
      package_facts:
        manager: auto

    - name: Install base workstation packages
      include: tasks/base_packages.yml
      become: true
      when: ansible_env.WORKSTATION

    - name: Update Alternatives
      include: tasks/alternatives.yml
      become: true
      when: ansible_env.WORKSTATION

    - name: Install docker 
      include: tasks/docker.yml
      become: true
      when: ansible_env.WORKSTATION

    - name: Install dnsmasq
      include: tasks/dnsmasq.yml
      become: true
      when: 
        - ansible_env.WORKSTATION
        - "'network-manager' in ansible_facts.packages"

    - name: Install Go
      include: tasks/go.yml
      become: true
      when: ansible_env.WORKSTATION

    - name: Install Local User and Group Membership
      include: tasks/user.yml
      become: true
      when: ansible_env.WORKSTATION
