- hosts: localhost
  tasks:
    - name: Install base workstation packages
      include: base_packages.yml
      become: true
      when: ansible_env.WORKSTATION

    - name: Install docker 
      include: docker.yml
      become: true
      when: ansible_env.WORKSTATION

    - name: Install Local User and Group Membership
      include: user.yml
      become: true
      when: ansible_env.WORKSTATION

    - name: Update Alternatives
      include: alternatives.yml
      become: true
      when: ansible_env.WORKSTATION

    - name: Enable dnsmasq
      include: dnsmasq.yml
      become: true
      when: ansible_env.WORKSTATION

    - name: Install Go
      include: go.yml
      become: true
      when: ansible_env.WORKSTATION

    - name: Install user packages
      include: user_packages.yml
