name: 'Check init scripts'

on:
  workflow_dispatch:
  push:
    paths:
      - 'init.sh'
      - 'ansible-init.sh'

jobs:
  check_init:
    name: Verify init script functionality
    runs-on: ubuntu-20.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install shellcheck

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Init Shellcheck
        run: |
          shellcheck init.sh ansible-init.sh

      - name: Run init.sh
        run: |
          sudo ./init.sh

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Run ansible-init.sh
        run: |
          ./ansible-init.sh ${{ steps.extract_branch.outputs.branch}}
