name: 'Check init script'

on:
  workflow_dispatch:
  push:
    paths:
      - 'init.sh'

jobs:
  check_init:
    name: Verify init.sh functionality
    runs-on: ubuntu-20.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install shellcheck

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run shellcheck
        run: |
          shellcheck init.sh

      - name: Run init.sh
        run: |
          sudo ./init.sh
